/************************************************************ 
The contents of this file are subject to the Pumpkin Salvo
License (the "License").  You may not use this file except
in compliance with the License. You may obtain a copy of
the License at http://www.pumpkininc.com, or from
warranty@pumpkininc.com.

Software distributed under the License is distributed on an
"AS IS" basis, WITHOUT WARRANTY OF ANY KIND, either express
or implied. See the License for specific language governing
the warranty and the rights and limitations under the
License.

The Original Code is Salvo - The RTOS that runs in tiny
places(TM). Copyright (C) 1995-2006 Pumpkin, Inc. and its
Licensor(s). All Rights Reserved.

$Source: C:\\RCS\\D\\Pumpkin\\Salvo\\Src\\MCC30\\salvohook_interrupt.c,v $
$Author: aek $
$Revision: 3.1 $
$Date: 2007-11-14 10:24:41-08 $

For Microchip MPLAB C30 C compiler and PIC24/dsPIC targets.

Default interrupt-control function for libraries. To be 
replaced by functions that control interrupts associated 
with Salvo services.

WARNING: Users -- DO NOT EDIT THIS FILE! To create your own
user hook(s), copy the code in this file to your own file,
modify the hook function(s) as required, and add the resulting
file to your project. The linker will override the default hook
function(s) in the Salvo library with your hook function(s)
of the same name(s).

************************************************************/
#include <salvo.h>


/************************************************************ 
****                                                     ****
**                                                         **
Hooks for Microchip MPLAB C30 C compiler -- blind control 
of global interrupts.

Interrupts will be disabled during Salvo's critical sections,
and will be re-enabled after them.

**                                                         **
****                                                     ****
************************************************************/
void OSDisableHook(void)
{
	__asm__ volatile("disi #0x3FFF");
}

void OSEnableHook(void)
{
	__asm__ volatile("disi #0x0000");
}

